#!/bin/bash

#####################################################
#
# Author: Dvorhack
#
# Goal: This script allow you to get,set profile 
#       for fan curves on asus gaming laptops
#
#####################################################

function usage {
    echo "Usage $0 <get|set|toggle>"
}

if [ -z "$1" ];then
    usage $0
    exit -1
fi

case $1 in
    "get")
        asusctl profile -p |cut -d' ' -f4
    ;;

    "set")
        available_cmd=("Performance" "Balanced" "Quiet")

        # Check if arg 2 is set and the profile is available
        if [[ -z "$2" || ! " ${available_cmd[*]} " =~ " $2 " ]];then
            echo "Usage: $0 set [${available_cmd[*]}]"
            exit -1
        fi

        asusctl profile -P $2 && notify-send -t 1000 -r 103 "$(asusctl profile -p)"
    ;;

    "toggle")
        asusctl profile -n && notify-send -t 1000 -r 103 "$(asusctl profile -p)"
    ;;

    "-h")
        usage $0
    ;;

    *)
        echo "Unknown command '$1'"
        usage $0
        exit -1
    ;;

esac

if [ "$1" == "get" ];then
    asusctl profile -p |cut -d' ' -f4
elif [ "$1" == "toggle" ];then
    asusctl profile -n && notify-send -t 1000 -r 103 "$(asusctl profile -p)"
fi